### ISSUE TITLE
This library causes UNEXPECTED TOP-LEVEL EXCEPTION error

### ISSUE THREAD

**Issue by alirezaaa** [Comcast/FreeFlow#89]
Hi,

I imported FreeFlow using jitpack and everything on building is okay but while I'm trying to debug my app UNEXPECTED TOP-LEVEL EXCEPTION will be thrown.

```
Information:Gradle tasks [:app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAfollestadMaterialDialogs0781Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72221Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2221Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72221Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42221Library UP-TO-DATE
:app:prepareComDaimajiaSliderLibrary115Library UP-TO-DATE
:app:prepareComGithubComcastFreeFlowV06Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase750Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesLocation750Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps750Library UP-TO-DATE
:app:prepareComOrhanobutHawk118Library UP-TO-DATE
:app:prepareComSoundcloudAndroidAndroidCrop100Library UP-TO-DATE
:app:prepareDeHdodenhofCircleimageview130Library UP-TO-DATE
:app:prepareIoReactivexRxandroid101Library UP-TO-DATE
:app:prepareMeGujunAndroidTaggroupLibrary14Library UP-TO-DATE
:app:preparePlCharmasAndroidAndroidReactiveLocation07Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJava UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug UP-TO-DATE
:app:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_80\bin\java.exe'' finished with non-zero exit value 2
Information:BUILD FAILED
Information:Total time: 8.212 secs
Information:1 error
Information:0 warnings
Information:See complete output in console
```
My current dependencies are
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')

    compile 'com.android.support:support-v4:22.2.1'
    compile 'com.android.support:design:22.2.1'
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.loopj.android:android-async-http:1.4.8'
    compile 'com.soundcloud.android:android-crop:1.0.0@aar'
    compile 'pl.charmas.android:android-reactive-location:0.7@aar'
    compile 'com.google.android.gms:play-services-location:7.5.0'
    compile 'io.reactivex:rxandroid:1.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.daimajia.slider:library:1.1.5@aar'
    compile 'com.orhanobut:hawk:1.18'
    compile 'com.mobsandgeeks:android-saripaar:2.0.2'
    compile 'de.hdodenhof:circleimageview:1.3.0'
    compile 'com.afollestad:material-dialogs:0.7.8.1'
    compile 'me.gujun.android.taggroup:library:1.4@aar'
    /*compile 'uk.co.ribot:easyadapter:1.5.0@aar'*/
    compile ('com.github.Comcast:FreeFlow:v-0.6'){
        exclude group: "com.android.support", module: "support-v4"
    }
}
```
I tried to exclude `com.android.support` library from the library but not worked. How can I fix this?

**Comment by alirezaaa** [comment]
Please help me!
